# Generated by Django 5.2.5 on 2026-01-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on Delivery'), ('wallet', 'Wallet')], max_length=20),
        ),
    ]
