# Generated by Django 6.0.1 on 2026-01-22 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
        ('orderapp', '0002_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='orderapp.order'),
            preserve_default=False,
        ),
    ]
