# Generated by Django 5.2.5 on 2025-11-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
